# Generated by Django 3.2.3 on 2022-04-18 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calendar_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('editable_by', models.ManyToManyField(related_name='editable_by', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visible_for', models.ManyToManyField(related_name='visible_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('AR', 'Arbeit'), ('FR', 'Freizeit')], default='FR', max_length=2)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycalendar.calendar')),
            ],
        ),
        migrations.CreateModel(
            name='RecurrentEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mycalendar.event')),
                ('frequence', models.CharField(choices=[('YE', 'Jährlich'), ('MO', 'Monatlich'), ('WE', 'Wöchentlich'), ('DA', 'Täglich'), ('HO', 'Stündlich')], default='WE', max_length=2)),
                ('interval', models.PositiveSmallIntegerField()),
            ],
            bases=('mycalendar.event',),
        ),
    ]
